export const arabicCountries = [
  "الأردن",
  "فلسطين",
  "مصر",
  "السعودية",
  "لبنان",
  "سوريا",
  "الإمارات",
  "العراق",
  "الكويت",
  "البحرين",
  "قطر",
  "عمان",
  "ليبيا",
  "تونس",
  "المغرب",
  "الجزائر",
  "السودان",
  "الصومال",
  "اليمن",
  "الهند",
];
export const arabicCountriesEn = [
  "Jordan",
  "Palestine",
  "Egypt",
  "Saudi Arabia",
  "Lebanon",
  "Syria",
  "United Arab Emirates",
  "Iraq",
  "Kuwait",
  "Bahrain",
  "Qatar",
  "Oman",
  "Libya",
  "Tunisia",
  "Morocco",
  "Algeria",
  "Sudan",
  "Somalia",
  "Yemen",
  "India",
];

export const jordanCities = [
  "عمان",
  "الزرقاء",
  "إربد",
  "العقبة",
  "مادبا",
  "الكرك",
  "معان",
  "السلط",
  "الطفيلة",
  "جرش",
  "المفرق",
];
export const jordanCitiesEn = [
  "Amman",
  "Zarqa",
  "Irbid",
  "Aqaba",
  "Madaba",
  "Karak",
  "Ma'an",
  "Salt",
  "Tafila",
  "Jerash",
  "Mafraq",
];

export const postions = [
  "عامل",
  "مشغل",
  "مساعد مشغل",
  "موزع",
  "مساعد موزع",
  "حارس",
];
export const locations = [
  "الادارة العامة",
  "المسلخ",
  "الفقاسة",
  "مزارع الامهات",
  "مصنع الاعلاف",
  "مصنع اللاحم",
  "مصنح اللحوم",
];
export const gender = [
  {
    value: "F",
    title: "انثى",
  },
  {
    value: "M",
    title: "ذكر",
  },
];
export const genderEn = [
  {
    value: "F",
    title: "female",
  },
  {
    value: "M",
    title: "male",
  },
];
export const highPraiortyCities = ["العقبة", "الكرك", "معان", "الطفيلة"];

export const meduimPraiortyCities = ["عمان", "الزرقاء", "مادبا", "السلط"];
export const lowPraiortyCities = ["إربد", "جرش", "المفرق"];
export const Religions = ["مسلم", "مسيحي", "أخرى"];
export const ReligionsEn = ["Muslim", "Christian", "Other"];
export const nationalityCountries = [
  "الأردن",
  "فلسطين",
  "مصر",
  "السعودية",
  "لبنان",
  "سوريا",
  "الإمارات",
  "العراق",
  "الكويت",
  "البحرين",
  "قطر",
  "عمان",
  "ليبيا",
  "تونس",
  "المغرب",
  "الجزائر",
  "السودان",
  "الصومال",
  "اليمن",
  "الهند",
  "ابناء اردنيات",
  "ابناء غزة",
];
export const nationalityCountriesEn = [
  "Jordan",
  "Palestine",
  "Egypt",
  "Saudi Arabia",
  "Lebanon",
  "Syria",
  "United Arab Emirates",
  "Iraq",
  "Kuwait",
  "Bahrain",
  "Qatar",
  "Oman",
  "Libya",
  "Tunisia",
  "Morocco",
  "Algeria",
  "Sudan",
  "Somalia",
  "Yemen",
  "India",
  "Children of Jordanian Mothers",
  "Children of Gaza",
];
export const locationsObj = {
  "الإدارة العامة": ["ضابط اداري"],
  "مزارع الأمهات": [
    "مساعد مدير مزرعة",
    "مساعد مشرف مزرعة",
    "مشرف مزرعة",
    "ضابط أمن",
    "مشرف رئيسي",
  ],
  "مزارع اللاحم": [
    " ضابط اداري",
    "مساعد مدير مزرعة",
    "مساعد مشرف مزرعة",
    "مساعد مشرف",
    "مشرف الأمن الحيوي",
    "منسق مزارع اللاحم",
    "مشرف نظافة",
    "سائق",
    "مشرف مزرعة ",
    "مدير  مزرعة",
    "عامل نظافة رئيسي",
    "مشرف مزرعة رئيسي",
  ],
  "الدائرة الهندسية والصيانة": [
    "فني صيانة",
    "مشرف صيانة",
    "مدير الدائرة الهندسية",
    "منسق مختبر وصيانة",
    "مدير صيانة ",
    "رئيس قسم صيانة المزارع والمشاريع",
    "فني كهرباء رئيسي",
    "فني صيانة رئيسي",
    "مهندس موقع - مصنع اللحوم",
  ],
  "مصنع الاعلاف": [
    "سائق",
    "سائق رافعة شوكية",
    "مدير التصنيع  ",
    "مدير انتاج",
    "مشرف انتاج",
    "سائق شاحنة",
    "مراقب ميزان",
  ],
  "الدائرة المالية": [
    "محاسب تكاليف",
    "محاسب ذمم مدينة",
    "محاسب عام",
    "محاسب خزينة",
    "رئيس قسم الذمم الدائنة",
    "أمين صندوق",
    "محاسب رئيسي",
    "مدير مالي",
    "رئيس قسم محاسبة المبيعات",
    "رئيس قسم التكاليف",
    " رئيس قسم  الذمم المدينة",
    "محاسب تكاليف رئيسي",
    "محاسب ذمم مدينة رئيسي",
    "محاسب عام رئيسي",
    "موظف تخطيط وتحليل مالي رئيسي",
  ],
  الفقاسة: [
    "مساعد مشرف",
    "مشرف استلام",
    "سائق",
    "منسق فقاسة",
    "مشرف انتاج",
    "عامل نظافة رئيسي",
  ],
  "الموارد البشرية": [
    "ضابط اداري",
    "سائق ",
    "مدير",
    "مشرف رواتب",
    "موظف اداري ومسؤول العلاقات العامة",
    "موظف استقبال",
    "موظف موارد بشرية رئيسي",
    "مشرف موارد بشرية",
  ],
  "تكنولوجيا المعلومات": [
    "مسؤول دائرة تكنولوجيا المعلومات",
    "مدير دائرة تكنولوجيا المعلومات",
    "مبرمج",
    "مبرمج رئيسي",
  ],
  "الدائرة القانونية": ["مستشار قانوني"],
  "دائرة التسويق": ["مدير", "اخصائي تسويق"],
  "مصنع اللحوم": [
    "مساعد مدير انتاج",
    "مدخل بيانات",
    "مشرف عمال",
    "مدير اداري (اقليم الجنوب)",
    "مدير انتاج",
    "منسق انتاج",
    "مشرف انتاج",
    "رئيس قسم التقطيع والتحضير",
    "رئيس قسم التشكيل والتغليف",
    "مشرف تعبئة رئيسي",
  ],
  "دائرة عمليات الدواجن": ["مدير صحة", "مدير عمليات"],
  "دائرة المشتريات والعمليات اللوجستية": [
    "مدير  عمليات التخطيط والامتياز",
    "مدير سلاسل التوريد",
    "موظف - قسم المواد الخام",
    "مهندس استدامة",
    "ممثل مشتريات",
    "رئيس قسم المشتريات",
    "رئيس قسم مشتريات الآلات الثقيلة",
    "رئيس قسم مواد الخام ومواد التعبئة",
    "رئيس قسم الخدمات اللوجستية والشحن",
    "اخصائي تخطيط العمليات",
    "أخصائي مشتريات",
  ],
  "دائرة توكيد الجودة": [
    "مساعد مدير الجودة والنوعية",
    "مهندس ",
    "فني صحة وسلامة مهنية",
    "فني مختبر",
    "مدير",
    "ممرض",
    "موظف مختبر",
    "رئيس قسم الانتاج الحيواني",
    "رئيس قسم",
    "مشرف مختبر رئيسي",
    "مشرف",
    "طبيب بيطري",
  ],
  "دائرة المبيعات": [
    "مسؤول خدمة عملاء رئيسي",
    "مدير تطوير الأعمال",
    "مدير المبيعات",
    "مدير مناطق",
    "منسق بضائع",
    "مروج",
    "مندوب",
    "مشرف مبيعات",
    "رئيس قسم خدمة العملاء",
    "مسؤول خدمة عملاء رئيسي",
    "مشرف مبيعات رئيسي",
  ],
  المسلخ: [
    "مساعد مدير",
    "مساعد مدير انتاج",
    "مساعد مشرف",
    "لحام",
    "مشرف قسم",
    "مشرف نظافة",
    "مسؤول قسم التقطيع",
    "مدخل بيانات",
    "مشرف عمال",
    "مدير المسلخ",
    "منسق انتاج",
    "مشرف انتاج",
    "مشرف علاقات عامة  مسلخ",
    "مراقب جودة",
    "سائق تنك نضح",
    "سائق شاحنة",
    "مراقب عمال التوزين",
    "مراقب ميزان",
  ],
  "دائرة المستودعات والتوزيع": [
    "مساعد رئيس قسم",
    "مساعد امين مستودع",
    "مدخل بيانات",
    "منسق اسطول المركبات",
    "سائق",
    "سائق رافعة شوكية",
    "فني كهرباء رئيسي",
    "مشرف عمال",
    "فني ميكانيك",
    "فني تكييف تبريد",
    "سائق براد",
    "مشرف مبيعات",
    "رئيس قسم التوزيع والاسطول",
    "مشرف مستودع رئيسي",
    "أمين مستودع رئيسي",
    "مشرف مستودع",
    "أمين مستودع",
    "مشرف مستودعات الادارة",
    "سائق شاحنة",
    "مشرف ورشة الصيانة",
    "رئيس قسم المستودعات",
    "مراقب ميزان",
  ],
};
export const locationsObjEn = {
  Administration: ["Administration Officer"],
  "Breeder Farms": [
    "Assistant Manager",
    "Assistant Supervisor",
    "Farm Supervisor",
    "Security Officer",
    "Sr. Supervisor",
  ],
  "Broiler Farms": [
    "Administration Officer",
    "Assistant Manager",
    "Assistant Supervisor",
    "Assistant",
    "Biosecurity Supervisor",
    "Broiler Farms Coordinator",
    "Cleaning Supervisor",
    "Driver",
    "Farm Supervisor",
    "Manager",
    "Sr. Cleaning Labor",
    "Sr. Farm Supervisor",
  ],
  "Engineering and Maintenance": [
    "Maintenance Technician",
    "Maintenance Supervisor",
    "Engineering Manager",
    "Laboratory & Maintenance Coordinator",
    "Maintenance Manager",
    "Section Head, Farms and Projects Mainte",
    "Senior Electrical Technician",
    "Senior Maintenance Technician",
    "Site Engineer",
  ],
  "Feed Mill": [
    "Driver",
    "Forklift Driver",
    "Manufacturing Manager",
    "Production Manager",
    "Production Supervisor",
    "Truck Driver",
    "Weight Controller",
  ],
  Finance: [
    "Cost Accountant",
    "Accountant, Credit & Accounts Receivable",
    "Accountant, General Ledger",
    "Accountant, Treasury",
    "AP Section Head",
    "Cashier",
    "Chief Accountant",
    "Finance Manager",
    "Sales Accounting Section Head",
    "Section Head, Costing",
    "Section Head, Credit & Accounts Receivable",
    "Sr. Accountant, Costing",
    "Sr. Accountant, Credit & Accounts Receivable",
    "Sr. Accountant, General Ledger",
    "Sr. Financial Planning & Analysis",
  ],
  Hatchery: [
    "Assistant Supervisor",
    "Dispatch Supervisor",
    "Driver",
    "Hatchery Coordinator",
    "Production Supervisor",
    "Sr. Cleaning Labor",
  ],
  "Human Resources": [
    "Administrator",
    "Driver",
    "Manager",
    "Officer",
    "Payroll Supervisor",
    "Administrative and Public Relations Officer",
    "Receptionist",
    "Sr. HR Officer",
    "HR Supervisor",
  ],
  IT: [
    "IT Administrator",
    "IT Manager",
    "Software Programmer",
    "Sr. Programmer",
  ],
  Legal: ["Legal Advisor"],
  Marketing: ["Manager", "Marketing Specialist"],
  MPP: [
    "Assistant Production Manager",
    "Data Entry Clerk",
    "Labor Foreman",
    "Administrative Manager",
    "Production Manager",
    "Production Coordinator",
    "Production Supervisor",
    "Section Head, Cutting & Preparing",
    "Section Head, Forming & Packaging ",
    "Sr. Supervisor, Canning",
  ],
  "Poultry Operations": ["Health Manager", "Operations Manager"],
  "Procurement and Logistics": [
    "Manager, Operations Planning & Excellence",
    "Supply Chain Manager",
    "Officer, Raw Material",
    "Planning Specialist",
    "Purchasing Representative",
    "Section Head, Purchasing",
    "Section Head, Purchasing Capital Equipment",
    "Section Head, RM & PM",
    "Section Head, Shipping & Logistics",
    "Specialist, Operation Planning",
    "Specialist, Purchasing",
  ],
  "Quality Assurance": [
    "Assistant Quality Assurance Manager",
    "Engineer",
    "Health and Safety Technician",
    "Lab Technician",
    "Manager",
    "Nurse",
    "Officer, Laboratory",
    "Head of Animal Production",
    "Section Head, Animal Care",
    "Section Head, Quality Assurance (MPP)",
    "Sr. Lab Supervisor",
    "Sr. QA & HSE Supervisor",
    "Supervisor, Quality Assurance",
    "Veterinary, Quality Assurance",
  ],
  Sales: [
    "Customer Service Executive",
    "Manager, Business Development",
    "Sales Manager",
    "Manager, Territory",
    "Merchandise Coordinator",
    "Promoter",
    "Sales Representative",
    "Sales Supervisor",
    "Section Head, Customer Service",
    "Sr. Customer Service Executive",
    "Sr. Sales Supervisor",
  ],
  Slaughterhouse: [
    "Assistant Manager",
    "Assistant Supervisor",
    "Butcher",
    "Section Supervisor",
    "Cleaning Supervisor",
    "Cutting Supervisor",
    "Data Entry Clerk",
    "Labor Foreman",
    "Slaughterhouse Manager",
    "Production Coordinator",
    "Production Supervisor",
    "Public Relations Supervisor",
    "Quality Inspector",
    "Tanker Driver",
    "Truck Driver",
    "Weight Control Foreman",
    "Weight Controller",
  ],
  "Warehouses and Distribution": [
    "Assistant Section Head, Warehouse & Dist",
    "Assistant Storekeeper",
    "Data Entry Clerk",
    "Fleet Coordinator",
    "Driver",
    "Forklift Driver",
    "Electrical Technician",
    "Labor Foreman",
    "Mechanical Technician",
    "Refrigeration Technician",
    "Refrigerated Driver",
    "Sales Supervisor",
    "Section Head, Fleet & Distribution",
    "Sr. Store Supervisor",
    "Sr. Storekeeper",
    "Store Supervisor",
    "Storekeeper",
    "Supervisor, Store (Finished Goods ADC)",
    "Truck Driver",
    "Vehicle Workshop Supervisor",
    "Warehouse Department Head",
    "Weight Controller",
  ],
};
export const universityOptions = [
  "University of Jordan",
  "Jordan University of Science and Technology",
  "Yarmouk University",
  "Hashemite University",
  "Al-Balqa Applied University",
  "Mutah University",
  "German-Jordanian University",
  "Philadelphia University",
  "Al Hussein Technical University",
  "Middle East University",
  "Jadara University",
  "Jerash University",
  "Al-Ahliyya Amman University",
  "World Islamic Sciences and Education University",
  "Zarqa University",
  "Princess Sumaya University for Technology",
  "Arab Open University",
  "Petra University",
  "Talal Abu-Ghazaleh University College of Business",
  "Other",
];
export const universityOptionsAr = [
  "جامعة الاردنية",
  "جامعة العلوم والتكنولوجيا الأردنية",
  "جامعة اليرموك",
  "جامعة الحسين",
  "الجامعة التطبيقية البلقاء",
  "جامعة مؤتة",
  "الجامعة الألمانية الأردنية",
  "جامعة فيلادلفيا",
  "الجامعة التكنولوجية الحسينية",
  "جامعة الشرق الأوسط",
  "جامعة الجادرا",
  "جامعة جرش",
  "الجامعة الأهلية عمان",
  "جامعة العلوم والعلوم الإسلامية العالمية",
  "جامعة الزرقاء",
  "جامعة الأميرة سمية للتكنولوجيا",
  "الجامعة العربية المفتوحة",
  "جامعة البتراء",
  "كلية طلال أبو غزالة لإدارة الأعمال",
  "أخرى",
];

export const majors = [
  "Computer Science",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Biology",
  "Chemistry",
  "Physics",
  "Mathematics",
  "Environmental Science",
  "Psychology",
  "Sociology",
  "Economics",
  "Business Administration",
  "Finance",
  "Marketing",
  "Political Science",
  "History",
  "English Literature",
  "Education",
  "Nursing",
  "Medicine",
  "Pharmacy",
  "Dentistry",
  "Law",
  "Architecture",
  "Graphic Design",
  "Film Studies",
  "Music",
  "Philosophy",
  "Environmental Engineering",
  "Geology",
  "Astronomy",
  "Anthropology",
  "Linguistics",
  "Art History",
  "Biotechnology",
  "Agricultural Science",
  "Aerospace Engineering",
  "Industrial Design",
  "Other",
];
export const majorsAr = [
  "علوم الحاسوب",
  "الهندسة الكهربائية",
  "الهندسة الميكانيكية",
  "الهندسة المدنية",
  "الهندسة الكيميائية",
  "علوم الأحياء",
  "الكيمياء",
  "الفيزياء",
  "الرياضيات",
  "علوم البيئة",
  "علم النفس",
  "علم الاجتماع",
  "الاقتصاد",
  "إدارة الأعمال",
  "التمويل",
  "التسويق",
  "علم السياسة",
  "التاريخ",
  "أدب اللغة الإنجليزية",
  "التعليم",
  "التمريض",
  "الطب",
  "الصيدلة",
  "طب الأسنان",
  "القانون",
  "الهندسة المعمارية",
  "تصميم الجرافيك",
  "دراسات السينما",
  "الموسيقى",
  "الفلسفة",
  "الهندسة البيئية",
  "علم الجيولوجيا",
  "علم الفلك",
  "الأنثروبولوجيا",
  "علم اللغة",
  "تاريخ الفن",
  "التكنولوجيا الحيوية",
  "علوم الزراعة",
  "الهندسة الجوفية",
  "تصميم الصناعي",
  "أخرى",
];

export const degreeOptions = [
  "Associate's Degree",
  "Bachelor's Degree",
  "Master's Degree",
  "Doctorate (Ph.D.)",
  "Professional Degree (MD, JD, etc.)",
  "High School Diploma or Equivalent",
  "Some College or Technical School",
  "Other",
];
export const degreeOptionsAr = [
  "درجة الدبلوم",
  "درجة البكالوريوس",
  "درجة الماجستير",
  "الدكتوراه (Ph.D.)",
  "الدرجة المهنية (MD، JD، إلخ.)",
  "شهادة الثانوية العامة أو ما يعادلها",
  "بعض الدراسة الجامعية أو المدرسة التقنية",
  "أخرى",
];
export const languageLevels = ["Basic", "Intermediate", "Professional"];
export const languageLevelsAr = ["أساسي", "متوسط", "محترف"];

export const marriageStatusAr = ["متزوج", "اعزب", "مطلق", "ارمل"];
export const marriageStatusEn = ["Married", "Single", "Divorced", "Widowed"];
export const extensionToType = {
  pdf: "PDF",
  doc: "Word",
  docx: "Word",
  png: "Image",
  jpg: "Image",
  jpeg: "Image",
};

export const iconMap = {
  PDF: "/assets/images/pdf.png",
  Word: "/assets/images/doc.png",
  Image: "/assets/images/image_icon.png",
};
